#!/usr/bin/env bash
# Bootstrap CCG AI orchestration in a project that uses ccg_project_orchestration as a submodule.
# Safe to re-run (idempotent).
#
# Usage:
#   orchestration_setup.sh [--project-root <path>] [--agents <slug,...>] \
#                          [--taskforge-url <url>] [--actor-id <uuid>]
#
# Flags:
#   --project-root   Root of the target project (default: $PWD)
#   --agents         Comma-separated agent slugs to pull immediately; omit to skip pull
#   --taskforge-url  Override TASKFORGE_BASE_URL for this run
#   --actor-id       Override CLAUDE_ORCH_ACTOR_ID for this run
set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "$(realpath "$0")")" && pwd)
ORCHESTRATION_ROOT=$(dirname "$SCRIPT_DIR")   # ccg_project_orchestration root

PROJECT_ROOT="$PWD"
AGENTS=""
ACTOR_ID_OVERRIDE=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --project-root)   PROJECT_ROOT="$2"; shift 2 ;;
    --agents)         AGENTS="$2";       shift 2 ;;
    --taskforge-url)  TASKFORGE_BASE_URL="$2"; shift 2 ;;
    --actor-id)       ACTOR_ID_OVERRIDE="$2"; shift 2 ;;
    *) echo "Unknown flag: $1" >&2; exit 1 ;;
  esac
done

[[ -n "$ACTOR_ID_OVERRIDE" ]] && export CLAUDE_ORCH_ACTOR_ID="$ACTOR_ID_OVERRIDE"

PROJECT_ROOT=$(realpath "$PROJECT_ROOT")

# ── Phase 0: env validation (only when a pull will run) ──────────────────────
if [[ -n "$AGENTS" ]]; then
  [[ -z "${TASKFORGE_API_KEY:-}" ]] && { echo "ERROR: TASKFORGE_API_KEY not set" >&2; exit 1; }
  [[ -z "${TASKFORGE_BASE_URL:-}" ]] && { echo "ERROR: TASKFORGE_BASE_URL not set" >&2; exit 1; }
fi

# ── Phase 1: directory structure ─────────────────────────────────────────────
ORCH_DIR="$PROJECT_ROOT/.orchestration"
AGENTS_DIR="$ORCH_DIR/agents"
mkdir -p "$AGENTS_DIR"
echo "Ensured $AGENTS_DIR"

GITIGNORE="$ORCH_DIR/.gitignore"
if [[ ! -f "$GITIGNORE" ]]; then
  cat > "$GITIGNORE" <<'EOF'
# Materialized agent personas — regenerated by `sync-persona pull`
agents/*.md
# Keep overlays (user-edited)
!agents/*.overlay.md
EOF
  echo "Created $GITIGNORE"
else
  echo "Skipped $GITIGNORE (already exists)"
fi

# ── Phase 2: install .claude/commands/ symlinks ───────────────────────────────
CMD_DIR="$PROJECT_ROOT/.claude/commands"
mkdir -p "$CMD_DIR"

ORCH_REL=$(realpath --relative-to="$PROJECT_ROOT" "$ORCHESTRATION_ROOT" 2>/dev/null \
           || echo "$ORCHESTRATION_ROOT")

for cmd in orch-start orch-stop setup-orchestration sync-persona; do
  TARGET="$ORCHESTRATION_ROOT/commands/${cmd}.md"
  LINK="$CMD_DIR/${cmd}.md"
  if [[ ! -e "$TARGET" ]]; then
    echo "WARNING: command template not found: $TARGET" >&2
    continue
  fi
  if [[ -L "$LINK" ]]; then
    echo "Skipped $LINK (symlink already exists)"
  elif [[ -f "$LINK" ]]; then
    echo "WARNING: $LINK exists as a plain file — not replacing with symlink" >&2
  else
    ln -s "../../${ORCH_REL}/commands/${cmd}.md" "$LINK"
    echo "Created symlink $LINK → ../../${ORCH_REL}/commands/${cmd}.md"
  fi
done

# ── Phase 3: stamp CLAUDE.md ──────────────────────────────────────────────────
CLAUDE_MD="$PROJECT_ROOT/CLAUDE.md"
SENTINEL="<!-- ccg-orchestration -->"

stamp_section() {
  cat <<EOF


$SENTINEL
## CCG AI Orchestration

This project uses [ccg_project_orchestration](${ORCH_REL}/) for AI-native task
coordination via [taskforge](https://github.com/DevinWilsonSC/agile_tracker).
Orchestration submodule path: \`${ORCH_REL}/\`

### Prerequisites
- \`TASKFORGE_API_KEY\` — API key for the \`claude_orch\` actor
- \`TASKFORGE_BASE_URL\` — taskforge instance URL (e.g. \`http://taskforge-prod:8000\`)
- \`CLAUDE_ORCH_ACTOR_ID\` — UUID of the \`claude_orch\` actor

### Slash commands (symlinked from orchestration submodule)
- \`/orch-start\`                             — start the periodic orchestrator loop
- \`/orch-stop\`                              — stop the loop
- \`/setup-orchestration\`                    — re-run bootstrap (idempotent)
- \`/sync-persona pull --slug <slug>\`        — pull a fresh agent persona
- \`/sync-persona propose --slug <slug>\`     — propose local overlay to taskforge
- \`/sync-persona status --slug <slug>\`      — check drift

### Agent personas
Materialized personas: \`.orchestration/agents/<slug>.md\` (gitignored — regenerated on pull).
Local customisation: \`.orchestration/agents/<slug>.overlay.md\` (committed — merged on pull).
EOF
}

if [[ ! -f "$CLAUDE_MD" ]]; then
  echo "# CLAUDE.md" > "$CLAUDE_MD"
  stamp_section >> "$CLAUDE_MD"
  echo "Created $CLAUDE_MD with orchestration section"
elif grep -qF "$SENTINEL" "$CLAUDE_MD"; then
  echo "Skipped CLAUDE.md stamp (section already present)"
else
  stamp_section >> "$CLAUDE_MD"
  echo "Appended orchestration section to $CLAUDE_MD"
fi

# ── Phase 4: write .orchestration/.env template ───────────────────────────────
ENV_FILE="$ORCH_DIR/.env"
if [[ ! -f "$ENV_FILE" ]]; then
  cat > "$ENV_FILE" <<'EOF'
# CCG orchestration env vars — source this file or set in shell profile.
# This file is gitignored; do not commit actual values.
export TASKFORGE_API_KEY=""
export TASKFORGE_BASE_URL="http://taskforge-prod:8000"
export CLAUDE_ORCH_ACTOR_ID=""
EOF
  echo "Created $ENV_FILE (fill in values)"
  # Ensure .env is gitignored
  ORCH_GITIGNORE="$ORCH_DIR/.gitignore"
  grep -qF '.env' "$ORCH_GITIGNORE" 2>/dev/null || echo '.env' >> "$ORCH_GITIGNORE"
else
  echo "Skipped $ENV_FILE (already exists)"
fi

# ── Phase 5: initial sync-persona pull ───────────────────────────────────────
if [[ -n "$AGENTS" ]]; then
  IFS=',' read -ra SLUG_LIST <<< "$AGENTS"
  for slug in "${SLUG_LIST[@]}"; do
    slug="${slug// /}"   # strip spaces
    [[ -z "$slug" ]] && continue
    echo "Pulling persona: $slug"
    if python3 "$ORCHESTRATION_ROOT/scripts/sync_persona.py" pull --slug "$slug" \
         --repo-root "$PROJECT_ROOT"; then
      echo "  ✓ $slug"
    else
      echo "  ✗ $slug (pull failed — run manually: /sync-persona pull --slug $slug)" >&2
    fi
  done
fi

echo ""
echo "orchestration_setup.sh complete."
echo "  .orchestration/      → $ORCH_DIR"
echo "  .claude/commands/    → symlinks to ${ORCH_REL}/commands/"
[[ -z "$AGENTS" ]] && echo "  No agents pulled. Run: /sync-persona pull --slug <slug>"
echo ""
echo "Next steps:"
echo "  1. Fill in $ENV_FILE (or set env vars in your shell profile)"
echo "  2. Commit: git add .orchestration/ .claude/commands/ CLAUDE.md"
echo "  3. Pull personas: /sync-persona pull --slug <slug>"
